name: Cypress

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.js'
      - '**/*.html'
      - '**/*.htm'
      - '**/*.css'
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.html'
      - '**/*.htm'
      - '**/*.css'

permissions:
  contents: read
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - uses: cypress-io/github-action@v5
        with:
          start: npx serve . -l 5500
          wait-on: http://localhost:5500
