name: Run Cypress Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.js'
      - '**/*.html'
      - '**/*.css'
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.html'
      - '**/*.css'

permissions:
  contents: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start web server
        run: npx serve -s . -l 5500 &
      - name: Wait for server
        run: npx wait-on http://localhost:5500

      - name: Cypress version
        run: npx cypress --version

      - name: Run Cypress tests
        run: npx cypress run
