name: ESLint

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.js'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.js'

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint and Cypress plugin
        run: |
          npm install eslint@^9 \
          eslint-plugin-cypress@latest \
          @microsoft/eslint-formatter-sarif@3.1.0 \
          --save-dev

      - name: Run ESLint
        run: npm run lint:js
        continue-on-error: true
