name: ESLint

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.js'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.js'

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint and Cypress plugin
        run: |
          npm install eslint@^9 \
          eslint-plugin-cypress@latest \
          @microsoft/eslint-formatter-sarif@3.1.0 \
          --save-dev

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npm run lint:js -- \
          --format @microsoft/eslint-formatter-sarif \
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
