name: Stylelint

on:
  push:
    branches: [main]
    paths:
    - '**/*.css'
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Stylelint Order plugin
        run: npm install stylelint-order --no-save

      - name: Run Stylelint
        run: npx stylelint "**/*.css" --formatter json > stylelint-errors.json

      - name: Save Stylelint errors
        uses: actions/upload-artifact@v3
        with:
          name: stylelint-errors
          path: stylelint-errors.json